repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: poetry run black
        language: system
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]
      - id: flake8
        name: flake8
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: poetry run flake8
        language: system
        types: [ python ]
        require_serial: true
        # TODO: expand this coverage to examples!
        files: '^(beaker|tests)/'
      - id: mypy
        name: mypy
        description: '`mypy` will check Python types for correctness'
        entry: poetry run mypy
        language: system
        types_or: [ python, pyi ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: '2.9.2'
        # TODO: expand this coverage to examples!
        files: '^beaker/'
