name: "Build workflow"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: formatting
        run: poetry run black --check .

      - name: linting
        run: poetry run flake8

      - name: type-checking
        run: poetry run mypy

      - name: start sandbox
        run: docker compose up -d

      - name: delay before testing
        run: sleep 10

      - name: pytest + coverage
        run: poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=beaker | tee pytest-coverage.txt

      - name: pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: stop sandbox
        run: docker compose down
